
services:
  zeebe:
    image: camunda/zeebe:8.5.0
    container_name: zeebe
    environment:
      - ZEEBE_LOG_LEVEL=info
      - ZEEBE_BROKER_GATEWAY_SECURITY_AUTHENTICATION_MODE=${ZEEBE_AUTH_MODE:-none}
      - ZEEBE_BROKER_EXPORTERS_ELASTICSEARCH_CLASSNAME=io.camunda.zeebe.exporter.ElasticsearchExporter
      - ZEEBE_BROKER_EXPORTERS_ELASTICSEARCH_ARGS_URL=http://elasticsearch:9200
    ports:
      - "26500:26500"
      - "9600:9600"
    volumes:
      - ../data/zeebe:/usr/local/zeebe/data
    networks:
      - orchestrator-network
    depends_on:
      - elasticsearch
    restart: unless-stopped

  operate:
    image: camunda/operate:8.5.0
    container_name: operate
    environment:
      - CAMUNDA_OPERATE_ZEEBE_GATEWAYADDRESS=zeebe:26500
      - CAMUNDA_OPERATE_ELASTICSEARCH_URL=http://elasticsearch:9200
      - CAMUNDA_OPERATE_ELASTICSEARCH_HOST=elasticsearch
      - CAMUNDA_OPERATE_ELASTICSEARCH_PORT=9200
      - SPRING_PROFILES_ACTIVE=dev
    ports:
      - "8081:8080"
    depends_on:
      - zeebe
      - elasticsearch
    networks:
      - orchestrator-network
    restart: unless-stopped

  tasklist:
    image: camunda/tasklist:8.5.0
    container_name: tasklist
    environment:
      - CAMUNDA_TASKLIST_ZEEBE_GATEWAYADDRESS=zeebe:26500
      - CAMUNDA_TASKLIST_ELASTICSEARCH_URL=http://elasticsearch:9200
      - SPRING_PROFILES_ACTIVE=dev
    ports:
      - "8082:8080"
    depends_on:
      - zeebe
      - elasticsearch
    networks:
      - orchestrator-network
    restart: unless-stopped

  connectors:
    image: camunda/connectors-bundle:8.5.0
    container_name: connectors
    environment:
      - ZEEBE_CLIENT_BROKER_GATEWAY-ADDRESS=zeebe:26500
      - ZEEBE_CLIENT_SECURITY_PLAINTEXT=true
      - CAMUNDA_OPERATE_CLIENT_URL=http://operate:8080
      - CAMUNDA_OPERATE_CLIENT_USERNAME=demo
      - CAMUNDA_OPERATE_CLIENT_PASSWORD=demo
    depends_on:
      - zeebe
      - operate
    networks:
      - orchestrator-network
    restart: unless-stopped

networks:
  orchestrator-network:
    external: true
